version: '3.4'
services:
  db: 
    image: vcolutti/mysql-rest-with-spring-boot-udemy  
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile   
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker 
      MYSQL_DATABASE: restfulspring
    ports: 
      - "3308:3306"  
    networks: 
      - udemy_network              
  rest-with-spring-boot-udemy:  
    image: vcolutti/rest-with-spring-boot-udemy  
    restart: always
    build: ./RestFulWithSpringAndDocker
    working_dir: /RestFulWithSpringAndDocker  
    environment: 
        TZ: America/Sao_Paulo   
        SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestFulWithSpringAndDocker:/RestFulWithSpringAndDocker
      - ~/.m2:/root/.m2
    ports:
        - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on: 
      - db
    networks: 
      - udemy_network                        
networks:
    udemy_network:
        driver: bridge            